## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("../Resources/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
application_df = application_df.drop(['EIN','NAME'], axis=1)
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [3]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE
application_count = application_df['APPLICATION_TYPE'].value_counts()
application_count

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T14        3
T25        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
application_types_to_replace = list(application_count[application_count < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE
classification_count = application_df['CLASSIFICATION'].value_counts()
classification_count

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C1732        1
C2600        1
C2570        1
C4120        1
C1236        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE
classification_count.loc[classification_count > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C6000       15
C1800       15
C1250       14
C8200       11
C1278       10
C1238       10
C1237        9
C1235        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C2710        3
C0           3
C1260        3
C1256        2
C1246        2
C3200        2
C1234        2
C1267        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
classifications_to_replace = list(classification_count.loc[classification_count < 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE
numeric_dummies_df = pd.get_dummies(application_df)
numeric_dummies_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [10]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
y = numeric_dummies_df['IS_SUCCESSFUL']
X = numeric_dummies_df.drop('IS_SUCCESSFUL', axis=1)

In [11]:
# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [12]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model (Attempt 1)

In [35]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
number_input_features = len(X_train_scaled[0])
hidden_layer1 = 40
hidden_layer2 = 15
nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=hidden_layer1, input_dim=number_input_features, activation="relu"))

# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=hidden_layer2, activation="relu"))


# Output layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_21 (Dense)            (None, 40)                1760

 dense_22 (Dense)            (None, 15)                615

 dense_23 (Dense)            (None, 1)                 16

=================================================================
Total params: 2,391
Trainable params: 2,391
Non-trainable params: 0
_________________________________________________________________

In [36]:
# Compile the model
#  YOUR CODE GOES HERE
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [37]:
# Train the model
#  YOUR CODE GOES HERE
fit_model = nn.fit(X_train_scaled,y_train,epochs=30)

Epoch 1/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5767 - accuracy: 0.7196
Epoch 2/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5548 - accuracy: 0.7286
Epoch 3/30
804/804 [==============================] - 1s 930us/step - loss: 0.5519 - accuracy: 0.7293
Epoch 4/30
804/804 [==============================] - 1s 944us/step - loss: 0.5497 - accuracy: 0.7312
Epoch 5/30
804/804 [==============================] - 1s 932us/step - loss: 0.5491 - accuracy: 0.7318
Epoch 6/30
804/804 [==============================] - 1s 971us/step - loss: 0.5487 - accuracy: 0.7319
Epoch 7/30
804/804 [==============================] - 1s 934us/step - loss: 0.5474 - accuracy: 0.7325
Epoch 8/30
804/804 [==============================] - 1s 950us/step - loss: 0.5471 - accuracy: 0.7325
Epoch 9/30
804/804 [==============================] - 1s 940us/step - loss: 0.5469 - accuracy: 0.7330
Epoch 10/30
804/804 [==============================] - 1s 981us/step - loss: 0.5462 - accuracy: 0.7329
Epoch 11/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5460 - accuracy: 0.7343
Epoch 12/30
804/804 [==============================] - 1s 939us/step - loss: 0.5456 - accuracy: 0.7330
Epoch 13/30
804/804 [==============================] - 1s 964us/step - loss: 0.5450 - accuracy: 0.7334
Epoch 14/30
804/804 [==============================] - 1s 968us/step - loss: 0.5449 - accuracy: 0.7348
Epoch 15/30
804/804 [==============================] - 1s 948us/step - loss: 0.5446 - accuracy: 0.7347
Epoch 16/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5447 - accuracy: 0.7340
Epoch 17/30
804/804 [==============================] - 1s 996us/step - loss: 0.5440 - accuracy: 0.7348
Epoch 18/30
804/804 [==============================] - 1s 964us/step - loss: 0.5438 - accuracy: 0.7356
Epoch 19/30
804/804 [==============================] - 1s 971us/step - loss: 0.5431 - accuracy: 0.7352
Epoch 20/30
804/804 [==============================] - 1s 971us/step - loss: 0.5435 - accuracy: 0.7352
Epoch 21/30
804/804 [==============================] - 1s 990us/step - loss: 0.5435 - accuracy: 0.7354
Epoch 22/30
804/804 [==============================] - 1s 933us/step - loss: 0.5427 - accuracy: 0.7357
Epoch 23/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5430 - accuracy: 0.7360
Epoch 24/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7345
Epoch 25/30
804/804 [==============================] - 1s 961us/step - loss: 0.5425 - accuracy: 0.7355
Epoch 26/30
804/804 [==============================] - 1s 966us/step - loss: 0.5420 - accuracy: 0.7356
Epoch 27/30
804/804 [==============================] - 1s 945us/step - loss: 0.5420 - accuracy: 0.7370
Epoch 28/30
804/804 [==============================] - 1s 940us/step - loss: 0.5422 - accuracy: 0.7362
Epoch 29/30
804/804 [==============================] - 1s 964us/step - loss: 0.5418 - accuracy: 0.7359
Epoch 30/30
804/804 [==============================] - 1s 1ms/step - loss: 0.5416 - accuracy: 0.7357

In [38]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5514 - accuracy: 0.7276 - 235ms/epoch - 877us/step
Loss: 0.5514201521873474, Accuracy: 0.727580189704895

In [39]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
nn.save("Models/AlphabetSoupCharity_Optimization1.h5")

# Compile, Train and Evaluate the Model (Attempt 2)

In [47]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
number_input_features = len(X_train_scaled[0])
hidden_layer1 = 100
hidden_layer2 = 80
nn_2 = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn_2.add(tf.keras.layers.Dense(units=hidden_layer1, input_dim=number_input_features, activation="relu"))

# Second hidden layer
#  YOUR CODE GOES HERE
nn_2.add(tf.keras.layers.Dense(units=hidden_layer2, activation="relu"))


# Output layer
#  YOUR CODE GOES HERE
nn_2.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_2.summary()

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_30 (Dense)            (None, 100)               4400

 dense_31 (Dense)            (None, 80)                8080

 dense_32 (Dense)            (None, 1)                 81

=================================================================
Total params: 12,561
Trainable params: 12,561
Non-trainable params: 0
_________________________________________________________________

In [48]:
# Compile the model
#  YOUR CODE GOES HERE
nn_2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [50]:
# Train the model
fit_model = nn_2.fit(X_train_scaled,y_train,epochs=80)

Epoch 1/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5348 - accuracy: 0.7404
Epoch 2/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5343 - accuracy: 0.7404
Epoch 3/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5343 - accuracy: 0.7395
Epoch 4/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5347 - accuracy: 0.7408
Epoch 5/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5345 - accuracy: 0.7400
Epoch 6/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5349 - accuracy: 0.7405
Epoch 7/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5344 - accuracy: 0.7412
Epoch 8/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5344 - accuracy: 0.7400
Epoch 9/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5341 - accuracy: 0.7407: 0s - loss: 0.5371 - accura
Epoch 10/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5337 - accuracy: 0.7402
Epoch 11/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5344 - accuracy: 0.7400
Epoch 12/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5340 - accuracy: 0.7399: 0s - loss: 0.5323 - ac
Epoch 13/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5340 - accuracy: 0.7407
Epoch 14/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5344 - accuracy: 0.7396
Epoch 15/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5343 - accuracy: 0.7407
Epoch 16/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5336 - accuracy: 0.7409
Epoch 17/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5335 - accuracy: 0.7403
Epoch 18/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5333 - accuracy: 0.7399
Epoch 19/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5337 - accuracy: 0.7401
Epoch 20/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5339 - accuracy: 0.7403
Epoch 21/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5332 - accuracy: 0.7404
Epoch 22/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5336 - accuracy: 0.7407
Epoch 23/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5336 - accuracy: 0.7406
Epoch 24/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5334 - accuracy: 0.7410
Epoch 25/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5338 - accuracy: 0.7406
Epoch 26/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5334 - accuracy: 0.7409
Epoch 27/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5334 - accuracy: 0.7408
Epoch 28/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5335 - accuracy: 0.7399
Epoch 29/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5332 - accuracy: 0.7404
Epoch 30/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5332 - accuracy: 0.7401
Epoch 31/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5339 - accuracy: 0.7403
Epoch 32/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5333 - accuracy: 0.7407
Epoch 33/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5337 - accuracy: 0.7405: 0s - los
Epoch 34/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5330 - accuracy: 0.7404
Epoch 35/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5328 - accuracy: 0.7402
Epoch 36/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5330 - accuracy: 0.7403
Epoch 37/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5331 - accuracy: 0.7407
Epoch 38/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5334 - accuracy: 0.7402
Epoch 39/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5331 - accuracy: 0.7409
Epoch 40/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5326 - accuracy: 0.7409
Epoch 41/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5331 - accuracy: 0.7409
Epoch 42/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5330 - accuracy: 0.7404
Epoch 43/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5335 - accuracy: 0.7402
Epoch 44/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5328 - accuracy: 0.7408
Epoch 45/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5337 - accuracy: 0.7404
Epoch 46/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5340 - accuracy: 0.7407
Epoch 47/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5327 - accuracy: 0.7401
Epoch 48/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5330 - accuracy: 0.7407
Epoch 49/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5329 - accuracy: 0.7402
Epoch 50/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5326 - accuracy: 0.7408
Epoch 51/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5330 - accuracy: 0.7407
Epoch 52/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5325 - accuracy: 0.7409
Epoch 53/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5327 - accuracy: 0.7408
Epoch 54/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5323 - accuracy: 0.7402
Epoch 55/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5320 - accuracy: 0.7413
Epoch 56/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5328 - accuracy: 0.7412
Epoch 57/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5326 - accuracy: 0.7410
Epoch 58/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5331 - accuracy: 0.7412
Epoch 59/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5334 - accuracy: 0.7408
Epoch 60/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5329 - accuracy: 0.7407
Epoch 61/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5327 - accuracy: 0.7406
Epoch 62/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5334 - accuracy: 0.7405
Epoch 63/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5318 - accuracy: 0.7407
Epoch 64/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5320 - accuracy: 0.7412: 0s - loss: 0.5296 - accu
Epoch 65/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5320 - accuracy: 0.7406
Epoch 66/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5335 - accuracy: 0.7406
Epoch 67/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5318 - accuracy: 0.7412
Epoch 68/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5318 - accuracy: 0.7411
Epoch 69/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5317 - accuracy: 0.7411
Epoch 70/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5320 - accuracy: 0.7410
Epoch 71/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5330 - accuracy: 0.7408
Epoch 72/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5321 - accuracy: 0.7413: 0s - loss:
Epoch 73/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5322 - accuracy: 0.7406
Epoch 74/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5329 - accuracy: 0.7402
Epoch 75/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5323 - accuracy: 0.7404
Epoch 76/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5321 - accuracy: 0.7418
Epoch 77/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5320 - accuracy: 0.7408
Epoch 78/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5317 - accuracy: 0.7404
Epoch 79/80
804/804 [==============================] - 1s 1ms/step - loss: 0.5318 - accuracy: 0.7411
Epoch 80/80

804/804 [==============================] - 1s 1ms/step - loss: 0.5319 - accuracy: 0.7413: 0s - loss: 0.5

In [46]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_2.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5746 - accuracy: 0.7279 - 176ms/epoch - 656us/step
Loss: 0.5745683908462524, Accuracy: 0.7279300093650818

In [51]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
nn.save("Models/AlphabetSoupCharity_Optimization2.h5")

# Compile, Train and Evaluate the Model (Attempt 3)

In [61]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
number_input_features = len(X_train_scaled[0])
hidden_layer1 = 180
hidden_layer2 = 100
nn_3 = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn_3.add(tf.keras.layers.Dense(units=hidden_layer1, input_dim=number_input_features, activation="relu"))

# Second hidden layer
#  YOUR CODE GOES HERE
nn_3.add(tf.keras.layers.Dense(units=hidden_layer2, activation="relu"))


# Output layer
#  YOUR CODE GOES HERE
nn_3.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_3.summary()

Model: "sequential_13"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_39 (Dense)            (None, 180)               7920

 dense_40 (Dense)            (None, 100)               18100

 dense_41 (Dense)            (None, 1)                 101

=================================================================
Total params: 26,121
Trainable params: 26,121
Non-trainable params: 0
_________________________________________________________________

In [62]:
# Compile the model
nn_3.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [63]:
# Train the model
fit_model = nn_3.fit(X_train_scaled,y_train,epochs=50)

Epoch 1/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5698 - accuracy: 0.7236
Epoch 2/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5560 - accuracy: 0.7286
Epoch 3/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5528 - accuracy: 0.7311
Epoch 4/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5510 - accuracy: 0.7309
Epoch 5/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5493 - accuracy: 0.7317
Epoch 6/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5489 - accuracy: 0.7328
Epoch 7/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5482 - accuracy: 0.7324
Epoch 8/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5476 - accuracy: 0.7338
Epoch 9/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5470 - accuracy: 0.7339
Epoch 10/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5461 - accuracy: 0.7352
Epoch 11/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5452 - accuracy: 0.7348: 0s - loss: 0.5461 - accuracy:
Epoch 12/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5449 - accuracy: 0.7351: 0s - loss: 0.5430 -
Epoch 13/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5451 - accuracy: 0.7357
Epoch 14/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5441 - accuracy: 0.7358
Epoch 15/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5438 - accuracy: 0.7362
Epoch 16/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5434 - accuracy: 0.7365
Epoch 17/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5437 - accuracy: 0.7362
Epoch 18/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5429 - accuracy: 0.7364
Epoch 19/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5427 - accuracy: 0.7372
Epoch 20/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5420 - accuracy: 0.7376
Epoch 21/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5419 - accuracy: 0.7363
Epoch 22/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5411 - accuracy: 0.7374
Epoch 23/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5416 - accuracy: 0.7378
Epoch 24/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5413 - accuracy: 0.7374
Epoch 25/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5404 - accuracy: 0.7383
Epoch 26/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5407 - accuracy: 0.7381
Epoch 27/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5403 - accuracy: 0.7377
Epoch 28/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5400 - accuracy: 0.7379
Epoch 29/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5400 - accuracy: 0.7372
Epoch 30/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5399 - accuracy: 0.7376
Epoch 31/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5397 - accuracy: 0.7386
Epoch 32/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5395 - accuracy: 0.7384
Epoch 33/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5389 - accuracy: 0.7381
Epoch 34/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5390 - accuracy: 0.7380
Epoch 35/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5386 - accuracy: 0.7385
Epoch 36/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5392 - accuracy: 0.7386
Epoch 37/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5386 - accuracy: 0.7389
Epoch 38/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5384 - accuracy: 0.7401
Epoch 39/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5382 - accuracy: 0.7389
Epoch 40/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5382 - accuracy: 0.7390
Epoch 41/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5381 - accuracy: 0.7392
Epoch 42/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5378 - accuracy: 0.7392
Epoch 43/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5377 - accuracy: 0.7391
Epoch 44/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5374 - accuracy: 0.7384
Epoch 45/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5372 - accuracy: 0.7394
Epoch 46/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5374 - accuracy: 0.7399
Epoch 47/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5379 - accuracy: 0.7398
Epoch 48/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5373 - accuracy: 0.7397
Epoch 49/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5370 - accuracy: 0.7386
Epoch 50/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5371 - accuracy: 0.7393

In [64]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_3.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5556 - accuracy: 0.7305 - 242ms/epoch - 904us/step
Loss: 0.555576741695404, Accuracy: 0.7304956316947937

In [65]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
nn.save("Models/AlphabetSoupCharity_Optimization3.h5")